### ISSUE TITLE
rack_dav implementation example

### ISSUE THREAD

**Issue by sudorado** [georgi/rack_dav#18]
I would want to display all the files from owncloud on a webpage on Rails which i'm creating. 

Can anyone give me an example which would explain the implementation of this gem ? The documentation of it does not say much for a newbie.

Thanks

**Comment by mrgordon** [comment]
To be honest, this ticket should still be open. Its quite difficult to find any examples without reading the entire spec suite for ideas. You end up on StackOverflow etc.
