### ISSUE TITLE
Wrong resource urls in response if RackDAV handler not mounted at '/'

### ISSUE THREAD

**Issue by child** [georgi/rack_dav#34]
My application has RackDAV handler mounted at /webdav, which prevents any client I tried from even showing any collection properly. The reason for that is that the urls in WebDAV responses are wrong, eg. www.mydomain.com/resource instead of www.mydomain.com/webdav/resource.

The problem is line 188 in controller.rb - if I add request.script_name there:

`xml.href "http://#{host}#{@request.script_name}#{url_escape resource.path}"`

all the clients start working properly.

**Comment by child** [comment]
The same is needed for line 125

**Comment by georgi** [comment]
Could you please make a pull request?
